// Auto-generated by `supabase gen types typescript --local > lib/supabase/types.ts`
// After running supabase db reset, regenerate this file.
// Placeholder until first generation.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
